version: '2.2'

services:
  kunafa-metrics:
    image: bizzotech/kunafa-metrics:v0.0.3
  main-db-metrics:
    image: gesellix/couchdb-prometheus-exporter
    command: 
    - -logtostderr
    - -couchdb.uri=http://main-db:5984
    - -couchdb.username=${COUCHDB_USER}
    - -couchdb.password=${COUCHDB_PASSWORD}
  public-db-metrics:
    image: gesellix/couchdb-prometheus-exporter
    command: 
    - -logtostderr
    - -couchdb.uri=http://public-db:5984
    - -couchdb.username=${COUCHDB_USER}
    - -couchdb.password=${COUCHDB_PASSWORD}
  cadvisor:
    image: google/cadvisor:v0.30.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${COUCHDB_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://dashboard.${HOST}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/
  proxy-server:
    expose:
      - '80'
      - '8090'
  

volumes:
  grafana_data: