{
 "title": "Kunafa",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Down CouchDB instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchdb_httpd_up) - sum(couchdb_httpd_up)"
    }
   ]
  },
  {
   "title": "Action Errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kunafa_events_docs_count) - sum(kunafa_events_docs_count{Status!=\"error\"})"
    }
   ]
  },
  {
   "title": "Request Failure in last 15m",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total{status=~'4.*|5.*'}[15m]))"
    }
   ]
  },
  {
   "title": "Request Duration > 1s in last 15m",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(sum(max(increase(nginx_http_request_duration_seconds_bucket[15m])) by (host)) - sum(max(increase(nginx_http_request_duration_seconds_bucket{le=\"01.000\"}[15m])) by (host)))"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kunafa_active_connections_count"
    }
   ]
  },
  {
   "title": "Active Polling users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(couchdb_httpd_clients_requesting_changes)"
    }
   ]
  },
  {
   "title": "Request Duration AVG in last 15m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_request_duration_seconds_sum[15m]) / increase(nginx_http_request_duration_seconds_count[15m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request Duration > 0.5 s in last 15m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(increase(nginx_http_request_duration_seconds_bucket[15m])) by(host)) - (max(increase(nginx_http_request_duration_seconds_bucket{le=\"00.500\"}[15m])) by(host))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests increase by host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total[15m])) by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests increase by status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total[15m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Current Docs Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kunafa_db_docs_count", "legendFormat": "{{Database}}" }
   ]
  },
  {
   "title": "Public DB Docs count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kunafa_public_docs_count", "legendFormat": "{{Type}}" }
   ]
  },
  {
   "title": "Current Action types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kunafa_events_docs_count) by(ActionType)",
     "legendFormat": "{{ActionType}}"
    }
   ]
  },
  {
   "title": "Current Actions status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kunafa_events_docs_count) by(Status)",
     "legendFormat": "{{Status}}"
    }
   ]
  },
  {
   "title": "Anonymous Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kunafa_anonymous_docs_count) by(ActionType)",
     "legendFormat": "{{ActionType}}"
    }
   ]
  },
  {
   "title": "Archived Docs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kunafa_archive_docs_count) by(ActionType)",
     "legendFormat": "{{ActionType}}"
    }
   ]
  },
  {
   "title": "Requests by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_requests_total) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_requests_total) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}